services:
  flask:
    # context: Dockerfile
    build: .
    depends_on:
      - postgres
    hostname: flask-app
    container_name: flask-app
    networks:
      - pg-network 
    ports:
    - 5000:5000
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pg-network  

volumes:
  pg-data:

networks:
  pg-network:
    driver: bridge